### ISSUE TITLE
AUV viewer - broken links

### ISSUE THREAD

**Issue by smancini** [aodn/auv#33]
Steps to reproduce:

Go to https://auv.aodn.org.au/auv/
Choose a AUV track (e.g.: Batemans201011 - Site4sz 09 Transect)
Click on the "Link to data folder"

What should happen:

The user is redirected to the appropriate directory on "data.aodn.org.au"

What does happen:

User get a 404 message.

See more information written by Laurent on this issue in the content repository (https://github.com/aodn/content/issues/200 )

**Comment by pmbohm** [comment]
@smancini @lbesnard 

This is the content.ftl file in question
https://github.com/aodn/geoserver-config/blob/0a53c129c0e1afd93cbb5b54b0768f5b8fd01fdb/workspaces/imos/JNDI_auv_viewer/auv_tracks_vw/content.ftl

### This part of interest "Link to data" is:
`<a  rel="external" href="${my.baseurlDataServer}/AUV/${feature.campaign_code.value}/${feature.site_code.value}" target="_blank" class="h3" alt=" download KML" >Link to data folder</a> <BR>
  `
### Which produces the html
```
  <a  rel="external" href="http://data.aodn.org.au/IMOS/AUV/SolitaryIs201208/r20120828_014649_si_04_PatchBroadLegs" target="_blank" class="h3" alt=" download KML" >Link to data folder</a> <BR>
```
The URL`http://data.aodn.org.au/IMOS/AUV/SolitaryIs201208/r20120828_014649_si_04_PatchBroadLegs` is broken. There is no `public` in the URL, so the content needs to be changed.

### What needs to be done
The rest of the links come from the database such as the dive reports and KML
##### content.ftl:52 ->
`<a href="${feature.dive_report.value}">Dive Report</a><BR>`
##### produces ->
http://data.aodn.org.au/IMOS/public/AUV/SolitaryIs201208/all_reports/r20120828_014649_si_04_PatchBroadLegs_report.pdf

1) Change `alt=" download KML"`  for the "Link to data folder" to `alt="Link to data folder"`
2) Fix all URL's in the database using the `href="${my.baseurlDataServer}/AUV/.....` construct so that the `baseurlDataServer` can be changed without requiring further content changes

**Comment by lbesnard** [comment]
https://github.com/aodn/content/issues/200

**Comment by lbesnard** [comment]
https://github.com/aodn/geoserver-config/pull/351

**Comment by lbesnard** [comment]
see last comment https://github.com/aodn/content/issues/200

**Comment by pblain** [comment]
Content issue - see above
